src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: ArticleRepository::class)]
class Article
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(['group_json'])]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['group_json'])]
    private ?string $texte = null;

    #[ORM\ManyToOne(inversedBy: 'article')]
    #[Groups(['group_json'])]
    private ?Utilisateur $utilisateur = null;

    #[ORM\OneToMany(mappedBy: 'article', targetEntity: Commentaire::class)]
    private Collection $commentaire;

    #[ORM\ManyToOne(inversedBy: 'articles')]
    #[Groups(['group_json'])]
    private ?Categorie $categorie = null;

    #[ORM\Column(length: 255)]
    #[Groups(['group_json'])]
    private ?string $Titre = null;

   

    public function __construct()
    {
        $this->commentaire = new ArrayCollection();
    }

    

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTexte(): ?string
    {
        return $this->texte;
    }

    public function setTexte(?string $texte): static
    {
        $this->texte = $texte;

        return $this;
    }
    public function __toString()
    {
        
        return $this->$texte;
    }

    public function getUtilisateur(): ?Utilisateur
    {
        return $this->utilisateur;
    }

    public function setUtilisateur(?Utilisateur $utilisateur): static
    {
        $this->utilisateur = $utilisateur;

        return $this;
    }

    /**
     * @return Collection<int, commentaire>
     */
    public function getCommentaire(): Collection
    {
        return $this->commentaire;
    }

    public function addCommentaire(commentaire $commentaire): static
    {
        if (!$this->commentaire->contains($commentaire)) {
            $this->commentaire->add($commentaire);
            $commentaire->setArticle($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): static
    {
        if ($this->commentaire->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getArticle() === $this) {
                $commentaire->setArticle(null);
            }
        }

        return $this;
    }

    public function getCategorie(): ?Categorie
    {
        return $this->categorie;
    }

    public function setCategorie(?Categorie $categorie): static
    {
        $this->categorie = $categorie;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->Titre;
    }

    public function setTitre(string $Titre): static
    {
        $this->Titre = $Titre;

        return $this;
    }


}

templates/BarreAdmin.html.twig
 <header class="navigation">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<nav class="navbar navbar-expand-lg p-0">
					<a class="navbar-brand" href="{{path('app_index')}}">
						<img class ="col-8" src="{{asset('images/logo.png')}}" alt="Logo">
					</a>

					<button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarsExample09" aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
						<span class="ion-android-menu"></span>
					</button>

					<div class="collapse navbar-collapse ml-auto" id="navbarsExample09">
						<ul class="navbar-nav ml-auto">
							<li class="nav-item active">
								<a class="nav-link" href="{{path('app_index')}}">Home</a>
							</li>
							<li class="nav-item @@service"><a class="nav-link" href="{{path('app_article_index')}}">Article</a></li>

							<div class="dropdown">
								<button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
								Categories
								</button>
								<ul class="dropdown-menu">
								{{ render(controller(
									'App\\Controller\\CategorieController::allCat'
								)) }}
								
								</ul>
							</div>

                            <li class="nav-item @@service"><a class="nav-link" href="{{path('app_utilisateur_index')}}">Utilisateur</a></li>

                            <li class="nav-item @@service"><a class="nav-link" href="{{path('admin')}}">Gestion</a></li>

							
							<li class="nav-item @@contact"><a class="nav-link" href="{{path('app_logout')}}">Déconnexion</a></li>
						</ul>
						{{ render(controller(
							'App\\Controller\\ArticleController::form'
						)) }}
					</div>
				</nav>
			</div>
		</div>
	</div>
</header>

templates/BarreConnectee.html.twig
 <header class="navigation">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<nav class="navbar navbar-expand-lg p-0">
					<a class="navbar-brand" href="{{path('app_index')}}">
						<img class ="col-8" src="{{asset('images/logo.png')}}" alt="Logo">
					</a>

					<button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarsExample09" aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
						<span class="ion-android-menu"></span>
					</button>

					<div class="collapse navbar-collapse ml-auto" id="navbarsExample09">
						<ul class="navbar-nav ml-auto">
							<li class="nav-item active">
								<a class="nav-link" href="{{path('app_index')}}">Home</a>
							</li>
							<li class="nav-item @@service"><a class="nav-link" href="{{path('app_article_index')}}">Article</a></li>

							<div class="dropdown">
								<button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
								Categories
								</button>
								<ul class="dropdown-menu">
								{{ render(controller(
									'App\\Controller\\CategorieController::allCat'
								)) }}
								
								</ul>
							</div>

                            <li class="nav-item @@service"><a class="nav-link" href="{{path('app_utilisateur_index')}}">Utilisateur</a></li>

							
							<li class="nav-item @@contact"><a class="nav-link" href="{{path('app_logout')}}">Déconnexion</a></li>
						</ul>
						{{ render(controller(
							'App\\Controller\\ArticleController::form'
						)) }}
					</div>
				</nav>
			</div>
		</div>
	</div>
</header>

templates/BarreDeconnectee.html.twig
 <header class="navigation">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<nav class="navbar navbar-expand-lg p-0">
					<a class="navbar-brand" href="{{path('app_index')}}">
						<img class ="col-8" src="{{asset('images/logo.png')}}" alt="Logo">
					</a>

					<button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarsExample09" aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
						<span class="ion-android-menu"></span>
					</button>

					<div class="collapse navbar-collapse ml-auto" id="navbarsExample09">
						<ul class="navbar-nav ml-auto">
							<li class="nav-item active">
								<a class="nav-link" href="{{path('app_index')}}">Home</a>
							</li>
							<li class="nav-item @@service"><a class="nav-link" href="{{path('app_article_index')}}">Article</a></li>
							<div class="dropdown">
								<button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
								Categories
								</button>
								<ul class="dropdown-menu">
								{{ render(controller(
									'App\\Controller\\CategorieController::allCat'
								)) }}
								
								</ul>
							</div>
                            <li class="nav-item @@service"><a class="nav-link" href="{{path('app_utilisateur_index')}}">Utilisateur</a></li>
							<li class="nav-item @@service"><a class="nav-link" href="{{path('app_apropos')}}">à propos</a></li>

							
							<li class="nav-item @@contact"><a class="nav-link" href="{{path('app_login')}}">Se connecter</a></li>
						</ul>
						{{ render(controller(
							'App\\Controller\\ArticleController::form'
						)) }}
						
					</div>
				</nav>
			</div>
		</div>
	</div>
</header>

templates/ListeCategories.html.twig
{% for categorie in categories %}
	<li class="dropdown-item @@service"><a class="nav-link" href="{{path('app_article_categorie', {'slug': categorie.slug})}}">{{ categorie.type }}</a></li>
{% endfor %}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        
            <!-- Basic Page Needs
            ================================================== -->
            <title>Blog Monument</title>

            <!-- Mobile Specific Metas
            ================================================== -->
            <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <meta name="description" content="Blog Monument">
            <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=5.0">
            <meta name="author" content="Themefisher">
            <meta name="theme-name" content="airspace">
            <meta name="generator" content="Themefisher Airspace Template v1.0">
            <!-- Favicon -->
            <link rel="shortcut icon" type="image/x-icon" href="{{asset("images/favicon.png")}}" />


            <!-- bootstrap.min css -->
            <link rel="stylesheet" href={{asset('plugins/bootstrap/bootstrap.min.css')}}>
            <!-- Ionic Icon Css -->
            <link rel="stylesheet" href={{asset('plugins/Ionicons/css/ionicons.min.css')}}>
            <!-- animate.css -->
            <link rel="stylesheet" href={{asset('plugins/animate-css/animate.css')}}>
            <!-- Magnify Popup -->
            <link rel="stylesheet" href={{asset('plugins/magnific-popup/magnific-popup.css')}}>
            <!-- Slick CSS -->
            <link rel="stylesheet" href={{asset('plugins/slick/slick.css')}}>
            
            <!-- Main Stylesheet -->
            <link rel="stylesheet" href={{asset('css/style.css')}}>
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {% block stylesheets %}
        {% endblock %}

        {% block javascripts %}
        {% endblock %}
    </head>

    
    <body>
    {% if is_granted('ROLE_ADMIN') %}
    
        {% include 'BarreAdmin.html.twig' %}

   {% elseif is_granted('ROLE_USER') %}
   
        {% include 'BarreConnectee.html.twig' %}
    
   {% else %}

        {% include 'BarreDeconnectee.html.twig' %}

   {% endif %}

        {% block body %}{% endblock %}
    </body>
    <!-- footer Start -->
<footer class="footer">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="footer-manu">
					<ul>
						<li><a href="about.html">About Us</a></li>
						<li><a href="contact.html">Contact us</a></li>
						<li><a href="service.html">How it works</a></li>
						<li><a href="faq.html">FAQ</a></li>
						<li><a href="pricing.html">Pricing</a></li>
					</ul>
				</div>
				<p class="copyright mb-0">Copyright <script>document.write(new Date().getFullYear())</script> &copy; Designed & Developed by <a
						href="http://www.themefisher.com">Themefisher</a>. All rights reserved.
					<br> Get More <a href="https://themefisher.com/free-bootstrap-templates/">Free Bootstrap
						Templates</a>
				</p>
			</div>
		</div>
	</div>
</footer>

<!--Scroll to top-->
<div id="scroll-to-top" class="scroll-to-top">
	<span class="icon ion-ios-arrow-up"></span>
</div>

    <!-- 
    Essential Scripts
    =====================================-->


    <!-- Main jQuery -->
    <script src="plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 3.1 -->
    <script src="plugins/bootstrap/bootstrap.min.js"></script>
    <!-- slick Carousel -->
    <script src="plugins/slick/slick.min.js"></script>
    <script src="plugins/magnific-popup/jquery.magnific-popup.min.js"></script>
    <!-- filter -->
    <script src="plugins/shuffle/shuffle.min.js"></script>
    <script src="plugins/SyoTimer/jquery.syotimer.min.js"></script>
    <!-- Google Map -->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"></script>
    <script src="plugins/google-map/map.js"></script>

    <script src="js/script.js"></script>
</html>

templates/dernierArticles.html.twig
{% for article in articles %}
<div>
     <i class="ion-quote"></i>
      <h1>{{ article.titre }}</h1>
      <p>"{{ article.texte }}"</p>
      <div class="user">
        <img src="images/item-img1.jpg" alt="Pepole">
        <p><span>Rose Ray</span> CEO-Themefisher</p>
      </div>
</div>
{% endfor %}

templates/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}

<!-- Slider Start -->
<section class="slider">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="block">
					<h1 class="animated fadeInUp">Bienvenue <br>  sur le blog monument</h1>
					<p class="animated fadeInUp">En association avec le G8-Patrimoine, </br>  un regroupement d'associations visant à sauvegarder notre patrimoine.</p>
					<a href="https://themefisher.com/free-bootstrap-templates/" class="btn btn-main animated fadeInUp" >Consulter nos articles</a>
				</div>
			</div>
		</div>
	</div>
</section>

<!-- Wrapper Start -->
<section class="about section">
	<div class="container">
		<div class="row">
			<div class="col-md-7">
				<div class="block">
					<div class="section-title">
						<h2>About Us</h2>
						<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the
							blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics</p>
					</div>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
						dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex
						ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat
						nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit
						anim id </p>
				</div>
			</div><!-- .col-md-7 close -->
			<div class="col-md-5">
				<div class="block">
					<img src="" alt="Img">
				</div>
			</div><!-- .col-md-5 close -->
		</div>
	</div>
</section>

<section class="feature bg-2">
  <div class="container">
    <div class="row justify-content-end">
      <div class="col-md-6">
        <h2 class="section-subtitle">WE BELIEVE IN GREAT IDEAS</h2>
        <p>Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce
          dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.
        </p>
        <p>Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce
          dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.
        </p>
        <p>Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce
          dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.
        </p>
        <a href="portfolio.html" class="btn btn-view-works">View Works</a>
      </div>
    </div>
  </div>
</section>

<!-- Service Start -->
<section class="service">
  <div class="container">
    <div class="row">
      <div class="col-12 text-center">
        <div class="section-title">
          <h2>Our Services</h2>
          <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, <br> there live the
            blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics</p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-3 col-md-4 col-sm-6">
        <div class="service-item">
          <i class="icon ion-coffee"></i>
          <h4>Branding</h4>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt </p>
        </div>
      </div>
      <div class="col-lg-3 col-md-4 col-sm-6">
        <div class="service-item">
          <i class="ion-compass"></i>
          <h4>Web Design</h4>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt </p>
        </div>
      </div>
      <div class="col-lg-3 col-md-4 col-sm-6">
        <div class="service-item">
          <i class="ion-image"></i>
          <h4>App Design</h4>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt </p>
        </div>
      </div>
      <div class="col-lg-3 col-md-4 col-sm-6">
        <div class="service-item">
          <i class="ion-bug"></i>
          <h4>Start Up</h4>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt </p>
        </div>
      </div>
      <div class="col-lg-3 col-md-4 col-sm-6">
        <div class="service-item">
          <i class="ion-headphone"></i>
          <h4>Logo Design</h4>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt </p>
        </div>
      </div>
      <div class="col-lg-3 col-md-4 col-sm-6">
        <div class="service-item">
          <i class="ion-leaf"></i>
          <h4>Development</h4>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt </p>
        </div>
      </div>
      <div class="col-lg-3 col-md-4 col-sm-6">
        <div class="service-item">
          <i class="ion-planet"></i>
          <h4>Brand Identity</h4>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt </p>
        </div>
      </div>
      <div class="col-lg-3 col-md-4 col-sm-6">
        <div class="service-item">
          <i class="ion-earth"></i>
          <h4>Brand Identity</h4>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt </p>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Call to action Start -->

<section class="call-to-action bg-1 section-sm overly">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="block">
					<h2 class="mb-3">We design delightful digital experiences.</h2>
					<p>Read more about what we do and our philosophy of design. Judge for yourself The work and results <br> we’ve
						achieved for other clients, and meet our highly experienced Team who just love to design.</p>
					<a class="btn btn-main btn-solid-border" href="contact.html">Tell Us Your Story</a>
				</div>
			</div>
		</div>
	</div>
</section>

<!-- Content Start -->
<section class="testimonial">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <div class="section-title text-center">
          <h2>Fun Facts About Us</h2>
          <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, <br> there live the
            blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics</p>
        </div>
      </div>
    </div>
    <div class="row align-items-center">
      <div class="col-md-6">
        <div class="block">
          <ul class="counter-box clearfix">
            <li>
              <div class="counter-item">
                <i class="ion-ios-chatboxes-outline"></i>
                <h4 class="count" data-count="99">0</h4>
                <span>Cups Of Coffee</span>
              </div>
            </li>
            <li>
              <div class="counter-item">
                <i class="ion-ios-glasses-outline"></i>
                <h4 class="count" data-count="45">0</h4>
                <span>Article Written</span>
              </div>
            </li>
            <li>
              <div class="counter-item">
                <i class="ion-ios-compose-outline"></i>
                <h4 class="count" data-count="125">0</h4>
                <span>Projects Completed</span>
              </div>
            </li>
            <li>
              <div class="counter-item">
                <i class="ion-ios-timer-outline"></i>
                <h4 class="count" data-count="200">0</h4>
                <span>Combined Projects</span>
              </div>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-md-5 col-md-offset-1">
        <div class="testimonial-carousel text-center">
          <div class="testimonial-slider owl-carousel">
            
            {{ render(controller(
									'App\\Controller\\ArticleController::dernierArticle'
								)) }}
             
            
            
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}


   